parameters:
#    pff_tag_it.example.class: Pff\TagItBundle\Example

services:
#    pff_tag_it.example:
#        class: %pff_tag_it.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
