parameters:
#    pff_tag_it.example.class: Pff\TagItBundle\Example

services:
    pff_tag_it.type.tagit:
        class: Pff\Bundle\TagItBundle\Form\Type\TagItType
        tags:
            - { name: form.type, alias: tagit }
